// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 执行状态
 */
export type ExecutionStatus = { "type": "Success" } | { "type": "Failed", "data": string } | { "type": "Skipped", "data": string };
