// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionResult } from "./ExecutionResult";

/**
 * 执行报告
 */
export type ExecutionReport = { deleted_count: number, deleted_bytes: bigint, packed_count: number, packed_bytes: bigint, preserved_count: number, pack_file_path: string | null, items: Array<ExecutionResult>, };
