// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { ExecutionStatus } from "./ExecutionStatus";

/**
 * 执行结果
 */
export type ExecutionResult = { item_id: string, action: Action, status: ExecutionStatus, detail: string | null, };
