// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分页结果
 */
export type PaginatedResult<T> = { items: Array<T>, total: number, page: number, page_size: number, };
