// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 预览结果
 */
export type PreviewResult = { "type": "Text", "data": string } | { "type": "Image", "data": string } | { "type": "Unsupported", "data": string };
