// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资源配置
 */
export type ResourceConfig = { cpu_limit_percent: number, unlimited: boolean, };
