// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { TraceCategory } from "./TraceCategory";

/**
 * 扫描结果轻量摘要（用于全选全部，避免加载完整 TraceItem）
 */
export type ScanResultSummary = { id: string, name: string, category: TraceCategory, suggested_action: Action | null, };
