// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionReport } from "./ExecutionReport";

/**
 * 会话状态机（FSM）
 *
 * 状态流转规则由 Orchestrator::is_valid_transition 严格校验。
 * 任何非法转换都会返回 OrchestratorError，防止误操作。
 */
export type SessionState = "Idle" | { "Scanning": { scan_id: string, } } | "Paused" | { "Scanned": { item_count: number, } } | "Confirming" | "Executing" | { "Completed": { report: ExecutionReport, } } | { "Failed": { reason: string, } };
