// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { TraceCategory } from "./TraceCategory";

/**
 * 单条痕迹
 */
export type TraceItem = { id: string, category: TraceCategory, scanner_id: string, name: string, path: string | null, size_bytes: bigint | null, modified_at: string | null, inferred: boolean, risk_note: string | null, suggested_action: Action | null, };
