// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { TraceCategory } from "./TraceCategory";

/**
 * 单条痕迹
 */
export type TraceItem = { id: string, category: TraceCategory, scanner_id: string, name: string, path: string | null, size_bytes: bigint | null, modified_at: string | null, inferred: boolean, risk_note: string | null, suggested_action: Action | null, 
/**
 * 来源分类：personal_desktop / personal_downloads / personal_documents / other
 */
source: string, 
/**
 * 文件类型分类：photo / video / audio / personal_doc / work_doc / code / archive / design / executable / temp / other
 */
file_type: string, };
