// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 痕迹类别
 */
export type TraceCategory = "Chat" | "Browser" | "System" | "Registry" | "FileSystem" | "DevTools" | "EnvVar";
